- _data/scripts.yaml
- scripts/trackbar.pl
the last version of
https://github.com/mjholtkamp/irssi-trackbar
> trackbar.pl version 1.7

- _data/scripts.yaml
- scripts/slack_emoji.pl
A script for converting Slack emoji to smileys.
> Add slack_emoji.pl

- _data/scripts.yaml
- scripts/twitter_theme.pl
> Add twitter_theme.pl

- README.markdown
- _data/scripts.yaml
- _testing/README.markdown
- _testing/config.yml
- _testing/report-test.zsh
- _testing/travis/autoinstall-perl-prereqs.zsh
- _testing/travis/update-scripts-yaml.pl
- scripts/email_privmsgs.pl
- scripts/emo.pl
- scripts/fnotify.pl
- scripts/greetignore.pl
- scripts/gsi.pl
- scripts/hipchat_complete.pl
- scripts/notes.pl
- scripts/tmux_away.pl
- scripts/trackbar.pl
- scripts/xmms.pl
Please follow the instructions in #11 *before* merging this PR
> Initial commit for automated scripts.yaml update

- _data/scripts.yaml
- scripts/kban-referrals.pl
Added kban-referrals.pl, which is a script that kickban users who post referral URLs in public messages in channels.
> Added kban-referrals.pl

- scripts/irssi_logger.pl
irssi_logger dumps chats to a PostgreSQL database for later review!
> Add irssi_logger

- scripts/xdccget.pl
Update xdccget.pl with some queue management and search capabilities. (pausing, retries, max parallel downloads).
Rework of help output.
> Update xdccget.pl with queue management and search

- scripts/whocount.pl
Produces a user count at the end of the output of /WHO.
> Add whocount.pl

- scripts/xmpp-notify.pl
https://github.com/dm8tbr/irssi-xmpp-notify/commit/48534a98490713834e2c87c5ca4b0a713f8e4f1e
> Importing XMPP-notify 1.0 from upstream

- scripts/mqtt-notify.pl
https://github.com/dm8tbr/irssi-mqtt-notify/commit/4b5144bce98d6e3f8ca97787b392c0fd079489ed
> Importing MQTT-notify 1.0 from upstream

- scripts/grepbans.pl
> Add grepbans.pl

- scripts/bansearch.pl
Add bansearch.pl to the script archive.
> Add bansearch.pl

- _data/scripts.yaml
- scripts/isbanned.pl
Added support for trailing characters in CIDR bans
> isbanned.pl

- scripts/8-ball.pl
The 8-ball script did not select from all possible answers, as `rand`
was not passed the size of all possible answers.
Fixed by changing the variable `answer` into an array and by selecting a
random index.
> Fixed a bug: selects from all ans; and added ans.

- _data/scripts.yaml
- scripts/track.pl
As requested. Was just easier for me to start from the beginning and create a fresh pull.
> Replaced hard-coded directory with Irssi::get_irssi_dir()

- scripts/sb_search.pl
> Add sb_search.pl

- _testing/_irssi_test.pl
> fix missing modification dates

- scripts/adv_windowlist.pl
- scripts/aspell.pl
- scripts/clearable.pl
- scripts/cmpchans.pl
- scripts/colorize_nicks.pl
- scripts/complete_at.pl
- scripts/dim_nicks.pl
- scripts/hideshow.pl
- scripts/hlscroll.pl
- scripts/ido_switcher.pl
- scripts/ircuwhois.pl
- scripts/linebuffer.pl
- scripts/messages_bottom.pl
- scripts/mouse-awl.pl
- scripts/mouse_soliton.pl
- scripts/nickcolor_expando.pl
- scripts/nickcolor_gay.pl
- scripts/nm2.pl
- scripts/recentdepart.pl
- scripts/sb_position.pl
- scripts/sbclearmatch.pl
- scripts/tmux-nicklist-portable.pl
- scripts/trackbar22.pl
- scripts/typofix.pl
- scripts/uberprompt.pl
```
18:33 < dx> ahf: should i forcefully submit to s.i.o all the scripts in nei's website?
18:33 < dx> FORCEFULLY
18:33 < Nei> hehe
18:33 < Nei> could be a good idea
18:34 < ahf> yes, do it with violence and chaos
18:34 < dx> hell yeah
```
:fire::fire::fire::fire::fire::fire::fire::fire::fire::fire:
:boom::boom::boom::boom::boom::boom::boom::boom::boom::boom:
:finnadie::finnadie::finnadie::finnadie::finnadie::finnadie::finnadie::finnadie::finnadie::finnadie:
Ok enough.
Using the `nei-scripts` branch in this same repository, feel free to push commits moving stuff around or deleting scripts that are considered too shitty to be in s.i.o. I just added all of them.
I renamed `mouse.pl` as `mouse-awl.pl`, since it seems to be an extension of it that isn't backwards compatible.
There was a newer …
> FORCEFULLY ADD ALL THE SCRIPTS FROM NEI'S WEBSITE

- scripts/xdcc_autoget.pl
ag_rem and ag_rembot now work again. Also deals well with reconnects.
> xdcc_autoget.pl: add functionality to deal with disconnects, fix issue with removing terms

- scripts/adv_windowlist.pl
- fixed regression bug /exec -interactive
> adv_windowlist 1.0a3

- scripts/tmux_away.pl
- correctly iterate client list
- add grace setting
> tmux_away 2.1

- scripts/execcmd.pl
Permit to use /EXEC with arbitrary irssi commands.
> Add execcmd 0.1

- scripts/dccrelay.pl
A script to forward incoming file transfers to another client.
> Add dccrelay 0.1

- _includes/footer.html
- assets/js/filtertable.js
- index.html
and fix some html closing tags.
> add javascript filter box to script website

- scripts/mh_sbuserinfo.pl
statusbar item that shows users and limit info in channels
changes:
only show item when channel is synced
cleaned out redundant code
> mh_sbuserinfo.pl v1.02

- scripts/mh_sbuserinfo.pl
statusbar item that shows users and limit info in channels
changes:
added setting _show_prefix and supporting code
changed setting _show_details_mode default to ON
updated documentation
> mh_sbuserinfo.pl v1.03

- scripts/mh_userstatus.pl
changes:
fixed bug when /whois spammed with status updates
added _noact_* and supporting code
added _show_mode and supporting code
> mh_userstatus.pl v1.01

- scripts/adv_windowlist.pl
- fixed some warnings in perl 5.10 reported by kl3
> adv_windowlist 1.0a4

- scripts/mh_sbsplitmode.pl
> mh_sbsplitmode.pl v1.00

- scripts/mh_sbsplitmode.pl
provides a statusbar item showing if your server is in splitmode and /splitmode to show detail
changes:
added _lag_limit and supporting code to skip /stats d on lag
will now print server is in splitmode in all relevant windows
> mh_sbsplitmode.pl v1.01

- scripts/linebuffer.pl
> linebuffer 0.3

- scripts/adv_windowlist.pl
- the last version had an incorrect fix. reported by kl3
> adv_windowlist 1.0a5

- scripts/mh_windowfill.pl
fill windows so scrolling starts bottom-up instead of top-down
changes:
added a few comments
> mh_windowfill.pl v1.05

- _data/scripts.yaml
- scripts/cap_sasl.pl
Uploading the final version while it's still relevant :D
> cap_sasl 1.11

- scripts/mh_sbsplitmode.pl
changes:
fixed bug where the timeout never got started
added a few comments
> mh_sbsplitmode.pl v1.02

- scripts/mh_userstatus.pl
changes:
fixed issue with disabling/enabling periodical /who
/whois bug was not entirely fixed, should be now
> mh_userstatus.pl v1.02

- scripts/mh_hold_mode.pl
known issues:
in the github version of irssi this script will not accept the keypad enter key
changes:
now accepts both 10 and 13 as keycode for enter, required to work in upcomming irssi
> mh_hold_mode.pl v1.02

- scripts/mh_sbsplitmode.pl
changes:
added setting _show_details_trend and supporting code
fixed warning about experimental feature (keys($var)) in perl v5.20.2
> mh_sbsplitmode.pl v1.04

- scripts/mh_userstatus.pl
changes:
added indents to /help
>  mh_userstatus.pl v1.03

- scripts/xdcc_autoget.pl
Irssi keeps saying 
```perl
Irssi: critical irssi_bless_iobject: assertion '(type & ~0xffff) == 0' failed"
```
> fix bug where attempt to download previously downloaded and deleted pack caused abberant behaviour

- scripts/mh_sbsplitmode.pl
changes:
added indents to /help
> mh_sbsplitmode.pl v1.05

- scripts/mirc_colour_popup.pl
add dynamic colour selection to popup
> mirc_colour_popup v1.1

- scripts/adv_windowlist.pl
- infinite loop on shortening certain window names reported by Kalan
> adv_windowlist 1.1

- scripts/bitlbee_typing_notice.pl
- Fix crash in Irssi during disconnect
> bitlbee_typing_notice 1.7.2

- scripts/mh_windowfill.pl
fill windows so scrolling starts bottom-up instead of top-down (screenshots in source)
changes:
> mh_windowfill.pl v1.06

- scripts/mh_hold_mode.pl
changes:
now using 'key send_line' instead of 'gui key pressed'
added /help
fixed '/hold_mode toggle', it didnt do anything before
code cleanup
changed url
> mh_hold_mode.pl v1.03

- scripts/mh_sbsplitmode.pl
changes:
added _print/_print_details and supporting code
/splitmode now prints stats d unavailable in a bit nicer way
now using individual redir numeric events for stats d
now does a stats d on netsplit/join
>  mh_sbsplitmode.pl v1.06

- scripts/mh_sbuserinfo.pl
statusbar item that shows users and limit info in channels
changes:
added setting _show_details_difference and supporting code
changed _show_warning_limit_percent default from 90 to 95
added a few comments
> mh_sbuserinfo.pl v1.04

- scripts/mh_userstatus.pl
> mh_userstatus.pl v1.04

- scripts/mh_hold_mode.pl
changes:
added mh_hold_mode_more_oldstyle and supporting code
added namespace to MSGLEVEL
code cleanup
> mh_hold_mode.pl v1.04

- scripts/aspell_complete.pl
This will be fixed on the irssi side too.
> aspell_complete: Fix crash when the dictionary is unset

- _testing/_irssi_test.pl
Fixes some issue that croped up in new Travis/Perl
> better package detection for multi-scripts

- scripts/mh_windowfill.pl
fill windows so scrolling starts bottom-up instead of top-down (screenshots linked in source)
changes:
changed url of screenshots because picpaste have a weird definition of forever
added namespace to MSGLEVEL
> mh_windowfill.pl v1.07

- scripts/mh_hold_mode.pl
changes:
moved default settings from hardcoded to irssi settings _default_hold_mode and _default_scroll_always
> mh_hold_mode.pl v1.05

- scripts/mh_sbsplitmode.pl
changes:
added namespace to MSGLEVEL
code cleanup
> mh_sbsplitmode.pl v1.07

- scripts/adv_windowlist.pl
* new format to choose abbreviation character
> adv_windowlist 1.2

- scripts/mh_userstatus.pl
changes:
added /whoa <nick> and /whoo <nick>
code cleanup
> mh_userstatus.pl v1.05

- scripts/mh_invite.pl
print invites in server, channel, query and active window
> mh_invite.pl v1.02

- scripts/bitlbee_hide_password.pl
- scripts/chansort_configurable.pl
- scripts/msg2notice_regex.pl
- scripts/munge_own_nickname_to_username.pl
- scripts/slack_strip_auto_cc.pl
These are all irssi scripts that I maintain & use myself that I think
are useful for general use, none of this has anything hardcoded related
to me and when applicable has a configurable interface.
> Submit my collection of scripts from my dotfiles.git

- scripts/munge_own_nickname_to_username.pl
I didn't think of the nick munger also needing to handle the /me format
when I first wrote this, it's a trivial fix so fix that.
> munge_own_nickname_to_username.pl: Also handle the /me form

- scripts/betterlist.pl
this script essentially applies grep.pl to LIST command output; it seemed like it might be more work to amend that script, so locally i've aliased list to this command which allows me to search list output
> new script betterlist.pl

- scripts/awayproxy.pl
> Will no longer default to sending e-mails to 'email@email.org' 

- scripts/replace.pl
Script to replace something said with regular expressions.
> Add replace.pl

- scripts/cap_sasl_fail.pl
- provide /set sasl_disconnect_on_fail for Irssi 0.8.18
> add cap_sasl_fail script

- scripts/chansort_configurable.pl
You'd have to have your sort function handle munging all the channels or
the rest would be in a randomized order, implement a stable sort here
and update the example to what I'm now using for my own sort which
doesn't munge the position of QUERY windows.
> scripts/chansort_configurable.pl: Make the sort stable

- scripts/logresume.pl
Decided to go ahead and just add this one, unless @ferret has any objections.
> Add logresume.pl

- scripts/autorun_scripts.pl
Uses Inotify to watch for updates in the autorun directory and takes appropriate action
> autorun scripts in the autorun directory

- _includes/footer.html
- assets/js/hashfill.js
- index.html
> support filling the javascript filter from url hash

- scripts/autoaway.pl
- scripts/mass_hilight_blocker.pl
- scripts/recentdepart.pl
Closes #94, fixes #152 and fixes #182
> Update mass_hilight_blocker, autoaway, and recentdepart

- scripts/fix_slackirc.pl
Some workarounds to improve irssi experience on the Slack IRC gateway
> Add fix_slackirc

- scripts/autowho.pl
periodically send /who to channels
> Add autowho script

- scripts/colon_emoji.pl
Replace words between :...: in messages according to a text file. Was
intended for Unicode Emoji on certain proprietary platforms.
> Add colon_emoji

- scripts/beforespace.pl
Rebind certain keys so that they are inserted before the space
> Add script beforespace

- scripts/settingshelp.pl
A copy of https://irssi.org/documentation/settings/ as /help script
> Add settingshelp

- scripts/mh_hold_mode.pl
changes:
fixed call to missing sub
> mh_hold_mode.pl v1.06

- scripts/chansort_configurable.pl
For the reasons covered in the commets I'm adding here the
${a,b}.{type,chatnet,name} would sometimes not be filled, which my
default sorter was assuming so it would end up spewing some warnings.
So change the filling of the defaults to that this is always filled, and
document what the value passed as $a or $b will look like.
Finally, change the default sorting from the more naïve example that
just mostly does alphabetic sorting to one that preserves the order of
the QUERY windows as they're created.
> chansort_configurable: Fix a bug & change the default

- scripts/mh_hold_mode.pl
changes:
corrected typo in instructions
added space to old-style more so it looks better
> mh_hold_mode.pl v1.07

- scripts/dim_nicks.pl
update dim_nicks to v0.4.7
- fix useless re-reading of settings colour
> dim_nicks 0.4.7

- _testing/config.yml
- scripts/mail.pl
> make mail.pl compile again

- scripts/urlinfo.pl
- remove formatting codes from messages prior to url scanning
- may fix #276
> urlinfo 1.4

- scripts/fix_slackirc.pl
> Update fix_slackirc to 0.2

- scripts/uberprompt.pl
* fix crash on /window close or /window hide with split windows
> uberprompt 0.3

- scripts/buffer.pl
I'm not entirely satisfied with this code, but I think it would work for most of the use cases.
> Add option -striptime in buffer.pl

- scripts/fix_slackirc.pl
* Improve fake host as to not confuse irssi on self msgs
> update fix_slackirc to 0.3

- scripts/fullwidth.pl
weechat ships with a similar script out of the gate as far as I know.
> added fullwidth

- scripts/cap.pl
Prints CAP lines sent from the server.  Code stolen from cap_sasl.pl
> CAP printing script

- scripts/anames.pl
> Improve anames nick prefix sorting

- scripts/iquiz.pl
- scripts/iquiz_en.pl
iQuiz is a quiz script featuring five types of games: classic Dizzy, Mieszacz, Familiada, Multi (Familiada without teams) and Pomieszany.
iquiz.pl - original script (Polish)
iquiz_en.pl - English translation
I had to do this a second time. After fixing an #311 pull I've uploaded wrong filenames (there is already quiz.pl in this repo so I renamed my script to iquiz.pl, but unfortunately while updating I've uploaded with the old name, made a mess and couldn't find a revert commit link…)
> Added iquiz.pl & iquiz_en.pl

- scripts/mh_sbuserinfo.pl
statusbar item that shows users and limit info in channels
changes:
added setting _show_details_oper and supporting code
added setting _format_sep and supportingf code
added setting _format_div and supporting code
added setting _group_begin and _format_group_end and supporting code
added setting _format_mode_oper, _format_mode_op, _format_mode_ho, _format_mode_vo and _format_mode_other, and supporting code
added settting _show_warning_limit_difference and supporting code (changing _show_warning_limit_percent behavior)
changed default of _show_warning_limit_percent from 95 to 0
> mh_sbuserinfo.pl v1.05

- scripts/rud_emotes.pl
Updated rud_emotes.pl script:
- added support for emotes in /me command (action)
- changed ugly formatted output text to fancy theme strings
- missing comma in IRSSI variable found and corrected
> Updated rud_emotes.pl script

- scripts/adv_windowlist.pl
- workaround for irssi issue #572
> adv_windowlist update to 1.3

- scripts/reorder.pl
* Add comments
* Add a VERSION
* Drop some silly features, eg autorun on load and network tags that got a trailing '2'
* Convert tabs to 4-space
* Use a valid contact email
> Clean up my reorder script

- scripts/listsort.pl
New script which sorts the results of /list by channel size.
> New listsort.pl script: order /list by chan size

- scripts/trackbar22.pl
* fix uninitialized warning reported by varazir
* add trackbar signals for use in other scripts
> update trackbar22 to v2.3

- scripts/desktop-notify.pl
irssi-1.0.0
bug found by jimgrape,  patched by xhebox.
https://github.com/irssi/scripts.irssi.org/issues/334
> desktop-notify.pl: process non-ascii msgs

- scripts/chanact.pl
fixes  #338 
fixes #336 
fixes #342
> chanact: update to v0.6.0

- scripts/hilightwin.pl
Setting parser inspired by irssi's own strarray_find_dest()
> hilightwin.pl: Add hilightwin_ignore_targets setting

- scripts/ctrlact.pl
Please see the comments in the script. I've now tested this for a week or so and thus would like to push it to this repo for wider exposure…
> ctrlact — Irssi script for fine-grained control of activity indication

- _testing/config.yml
- scripts/hitcount.pl
travis: hitcount 	✘ 	✔ 	✔ 	4 	☡ 	(c)
* move the instructions from sub hitcount to sub  refresh_hitcount
* correct initializing of the variables
> [hitcount] re arrange the script

- scripts/fullrain.pl
Merging features of [rainbow.pl](https://github.com/irssi/scripts.irssi.org/blob/master/scripts/rainbow.pl) with [fullwidth.pl](https://github.com/irssi/scripts.irssi.org/blob/master/scripts/fullwidth.pl) into one script without depending on the other two.
> Add fullrain.pl v1.0

- scripts/adv_windowlist.pl
- fix line wrapping in some themes, reported by @justanotherbody
- fix named window key detection, reported by @madduck
- make title (in viewer and shared_sbar) configurable
> adv_windowlist.pl: update to 1.4

- scripts/fullwidth.pl
added help text/command
added feature to only fullwidth text between two stars (*).
> updated fullwidth

- scripts/mh_sbuserinfo.pl
statusbar item that shows user count (opers, ops, halfops, voice and total) and limit info (with opless/limit warning) in channels
changes:
added 'sbitems' to irssi header for better scriptassist.pl support (github issue #1)
added _show_details_away/_format_mode_away and supporting code
some description and documentation changes
> mh_sbuserinfo.pl v1.06

- scripts/mh_hold_mode.pl
changes:
added 'sbitems' to irssi header for better scriptassist.pl support (github issue 1)
> mh_hold_mode.pl v1.08

- scripts/mh_sbsplitmode.pl
changes:
added 'sbitems' to irssi header for better scriptassist.pl support (github issue 1)
> mh_sbsplitmode.pl v1.08

- scripts/adv_windowlist.pl
- scripts/trackbar22.pl
* improve sideways split compat
> update adv_windowlist and trackbar22

- scripts/sysinfo277-irssi.pl
Illegal division by zero at line 408
> [sysinfo277-irssi] Bug #356

- scripts/nicklist.pl
Fix a warning in cmd_scroll where it's possible that there is no channel, but the nicks are retrieved before that check.
Add toggle functionality to make it easier to turn nicklist on and off with a single bound key.
> Fix warning, add toggle function to nicklist

- scripts/tmux-nicklist-portable.pl
- improve performance especially on /wc
> update tmux-nicklist-portable to 0.1.6

- scripts/nicklist.pl
unbreak a change that broke scrolling in nicklist 0.4.8
reported by @kiero
> nicklist.pl 0.4.9 - fix scrolling

- scripts/ziew.pl
added one of my old scripts, still available in the PLD Linux , but nowadays things seem to be done over GitHub.
> add ziew.pl script

- scripts/urlgrab.pl
> Include https URLs in urlgrab.pl

- scripts/showinactive.pl
> Add showinactive, yet another hilightwin script

- scripts/toilet.pl
Hello! Adding new script. Quite similar to figlet's but using toilet instead (color support, cool fonts, and I'll probably add a few more options later).
> Adding new script. Simple toilet implementation for Irssi.

- scripts/discord_unhilight.pl
Used to remove annoying self hilights when using discord to irc bridge on channels
> discord_unhilight.pl first version

- scripts/toilet.pl
Added general filters instead of just the "gay" filter. Each filter is separated with a ":" character.
> toilet.pl: Added filters

- scripts/deadbeef.pl
deadbeef control and now playing script
> Add deadbeef.pl

- scripts/trigger.pl
* Allow notify trigger types to use -masks
They have masks, so allow matching them.
* Allow matching old nick using -other_masks for nick changes
Matching the old nick has its uses, so shoehorn it under -other_masks.
* Add -last option; if trigger with this option matched, doesn't
process any more triggers for that message
Useful if the trigger's action does something like kickban or akill.
* Allow moving triggers entirely by name
Useful for programmatic rearranging of triggers, as you don't need to
know the number of the target.  First trigger will be placed before
second trigger.  (Goes well with -last, too)
> trigger.pl: various improvements

- scripts/colon_emoji.pl
This PR implements the TODO of handling outgoing messages. It also adds two config options to toggle outgoing and incoming replacements separately.
> [colon_emoji.pl] Add support to handle outgoing messages

- scripts/nickcolor.pl
- Fix issue #438
- Add two new functionalities (requested in https://github.com/irssi/irssi/issues/800).
> [nickcolor.pl] Fix wrong output. Add two new (optional) functionalities

- scripts/bantime.pl
> [bantime][#7] update bantime.pl

- scripts/cap-extjoin.pl
> [cap-extjoin]  add cap-extjoin.pl

- scripts/dejunk.pl
> [dejunk][#450] time optimizing

- scripts/query_whois.pl
> [query_whois][#7] add query_whois.pl

- scripts/banaffects.pl
> [banaffects][#7] add banaffects.pl

- scripts/quakequit.pl
> [quakequit][#7] add quakequit.pl

- README.markdown
- travis_report.markdown
> Add documentation about reading travis test report

- _data/scripts.yaml
- scripts/smartfilter.pl
I noticed the [smartfilter repo](https://github.com/lifeforms/irssi-smartfilter) has changes not reflected here. I grabbed the latest source and updated the `scripts.yaml` file with the latest metadata from the repo.
This is my first time creating a pull request, so let me know if I'm overlooking anything! Thanks!
> Update smartfilter.pl script to 0.4

- scripts/toggle_winlevels.pl
Requires PR https://github.com/irssi/irssi/pull/746
> script to toggle hidden levels in windows

- scripts/scriptassist.pl
> [scriptassist] improve autorun creation

- scripts/hilite_url.pl
Reaction to https://github.com/irssi/scripts.irssi.org/pull/329#commitcomment-20939744
> [hilite_url] Make the url color configurable

- scripts/nicklist.pl
@coekie 
https://github.com/coekie/irssi-scripts/blob/master/nicklist.pl
http://wouter.coekaerts.be/tmp/nicklist.pl
* Add support for 'other' modes (&~,...)
* Give different (configurable) colors to friends, dependant on flags.
* Fix another screen sizing issue
> [nicklist][#486] add patch 0.4.6+

- scripts/washnicks.pl
> [washnicks] add setting washnicks_channels

- scripts/findbot.pl
I am not associated with this project since 10 years ++
> remove henrik from this file

- scripts/findbot.pl
- requesting in a private message is allowed when user is in a monitored channel
- filelist creation script at the bottom of this script has been changed to support utf8, multiple folders, with or without file and 7z compression of the command list
> [findbot.pl] private message requests are allowed and changed filelist creation

- scripts/irssi-feed.pl
@jcaesar
* small repairs and help
* Fix empty titlelines.
* Fix initial line space
* Fix setting a feed URI
* Fix relative redirects Update info
* Add a check for a correct servertag and reformat output of João Orui's print to channel
* Add an option which allows sending updates to a channel
> [Irssi-feed] update

- scripts/away_hilight_notice.pl
> [away_hilight_notice] version 15.01.01

- scripts/active_notice.pl
> [active_notice] version 15.01.01

- scripts/pushsafer.pl
Add new Pushsafer Parameter, IconColor, Priority, Retry, Expire, Answer.
Based on the [Pushsafer API](https://www.pushsafer.com/en/pushapi)!
> Add new Pushsafer Parameter

- scripts/slack_complete.pl
* Support for common mentions (@here, @channel, @everyone)
* Use completion_char setting instead of hard coded colon
* Option to not add completion_char when completing first word of current line
> Feature update for slack_complete.pl

- scripts/twtopic.pl
bug: reported by Koffa (freenode#irssi)
> [twtopic] add value check for 'twtopic_refresh'

- scripts/spell.pl
spell_ispell_path
spell_use_dictionary
@mkowalchuk
> [spell] add options

- scripts/UNIBG-autoident.pl
> [UNIBG-autoident] fix the connection to the NS bot

- scripts/trackbar.pl
Disables clearing of the trackbar, if desired.
> [trackbar.pl] add new all_manual setting

- scripts/adv_windowlist.pl
* add detach setting to hide windows
* fix race condition when loading the script, reported by madduck
* improve compatibility with Irssi 1.2
> [adv_windowlist] update to adv_windowlist 1.6

- scripts/settingshelp.pl
I broke it, I get to pick up the pieces
> [settingshelp] fix download url

- scripts/cmdind.pl
* add detection for // heuristic
> [cmdind] update to 1.1

- scripts/fakectcp.pl
> [fakectcp] #535 change signal

- scripts/mood.pl
> [mood] fix a regex

- scripts/dns.pl
inspired by wMw freenode#irssi (2018-12-31)
> [dns] add ipv6

- scripts/rud_emotes.pl
- fixed messages containing utf-8 characters
- added tab-completion to emotes
- added "rud_emotes_space_after_completion" settings flag
> [rud_emotes] Added utf-8 support and auto-completion.

- _testing/config.yml
- scripts/on.pl
> [on][crit] new option

- scripts/autolimit.pl
> [autolimit] change the config to irssi

- scripts/file.pl
> [file] Getopt::Long

- scripts/emaildb.pl
> [emaildb] version 1.2

- scripts/remote.pl
> [remote] move the setting to irssi

- scripts/bitlbee_blist.pl
> [bitlbee_blist] version 0.5

- scripts/adv_windowlist.pl
-  use string_width in Irssi 1.2.0
> [adv_windowlist] update to 1.8

- scripts/leodict.pl
> [leodict] new connector

- scripts/keepnick.pl
> [keepnick] version 1.19

- _testing/autoinstall-perl-prereqs.zsh
> [travis] protect scan-perl-prereqs

- scripts/trackbar.pl
- fix /^join bug
fixes #561, fixes #550 and fixes #566
> [trackbar] update to 2.8

- scripts/dim_nicks.pl
- fix default setting not working
reported by Koffa
> [dim_nicks] update to 0.4.9

- scripts/trigger.pl
> [trigger] add send_text to allchan_types

- scripts/settingshelp.pl
- fix markdown escapes in tables
> [settingshelp] update to 1.3

- scripts/theme.pl
> [theme] help if noargs

- scripts/mouse.pl
expand the check of supported terminals to include the [kitty](https://sw.kovidgoyal.net/kitty/) terminal
> [mouse] Support kitty terminal

- scripts/kban-referrals.pl
> [kban-referrals] smartmatch, completion

- scripts/mouse_soliton.pl
> [mouse_soliton] name

- scripts/hideshow.pl
use /window hidelevel from Irssi 1.1
> [hideshow] update to 0.4.5

- scripts/email_msgs.pl
> [email_msgs] config to irssi

- scripts/bansearch.pl
> [bansearch] format, redir, event 352, 354

- scripts/pangotext.pl
> [pangotext] utf8

- scripts/urlwindow.pl
as per request, urlwindow.pl now supports handling gopher links and ftp
> [urlwindow] amended regexp to include ftp and gopher links

- scripts/sysinfo277-irssi.pl
Signed-off-by: Matt Bentley <mbentley@mbentley.net>
> [sysinfo277-irssi] Added armv7l support for Raspberry Pi

- scripts/revolve.pl
Adding irssi-revolving-door per rfreebern/irssi-revolving-door#10
> Add irssi-revolving-door script

- scripts/copy.pl
> [copy] v0.04

- scripts/matryoshka.pl
> [matryoshka] add matryoshka.pl

- scripts/trigger.pl
Fixes triggers that modify message text changing `$`, `;`, and `\` in captured text into `\$`, `\;`, and `\\` in the replacement.
> trigger.pl: only escape replacement into commands, not normal messages

- scripts/gitscriptassist.pl
* small korrekt in help
* add modified in info command
* git fetch and pull reload scripts.yaml
* bug with $/
> [gitscriptassist] v0.2

- scripts.yml
- scripts/scriptassist.pl
> [scriptassist] change eval to yaml

- scripts/tab_stop.pl
I found this version of `tab_stop.pl` on my disk.
Your version is newer (2011052400->2002123102)
Please review before merging.
> [tab_stop.pl] Update to newer version which I found on my disk

- scripts/unread.pl
small script to reset a window to unread status
> add new script : unread.pl

- scripts/perlalias.pl
Previously, these functions would fail with a critical warning because irssi doesn't resolve a calling script object.
This will allow these to work and be used: signals/commands registered during execution will get removed after execution completes, while those added during compilation (via BEGIN/UNITCHECK) will stay for the life of the alias.
> Update perlalias.pl to handle use of signal_add/command_bind

- scripts/scriptassist.pl
- do not look up numbers if window_number_commands is on
- fix circular references in get_unknown
- restore comment of unfinished "depends" code
- fix top/ratings/rate
> [scriptassist] update to 2020042700

- scripts/adv_windowlist.pl
> [adv_windowlist] update to 1.9

- scripts/trackbar.pl
- fix crash on /mark in empty window
fixes #706
> [trackbar] update to 2.9

- scripts/colorize_nicks.pl
port to Irssi 1.3 ABI 28
#708 
https://github.com/irssi/irssi/issues/1189
> [colorize-nicks] update to 0.4.0

- scripts/nickcolor_gay.pl
port to Irssi 1.3 ABI 28
#708
irssi/irssi#1189
> [nickcolor_gay] update to 0.2

- scripts/munge_own_nickname_to_username.pl
port to Irssi 1.3 ABI 28
#708
irssi/irssi#1189
> [munge_own_nickname_to_username] update to 1.2

- scripts/ding.pl
This is a script that can be configured to play notification noises for all messages, private messages, or hilighted messages, using mpg123 and aplay.
> New Script: ding.pl

- scripts/telegram-notify.pl
Notifies the user over telegram whenever they get a PM or a hilighted
message.
> New script: telegram-notify.pl

- scripts/twitch_notify.pl
New script to print to the status window when a twitch channel has come online/offline.
> twitch_notify: init at 0.0.1

- scripts/copy.pl
feature request fulfillment #725
> [copy.pl] Added copy of several rows

- scripts/adv_windowlist.pl
> [adv_windowlist] update to 1.9.1

- scripts/sbmove.pl
A script to move scrollback text to another window
> add sbmove script

- scripts/conceal.pl
a script to hide nickserv passwords when typing them manually
> add conceal script

- scripts/merge_resources.pl
this script will automatically group multiple XMPP queries from different
resources of the same person, and automatically unquery old resources.
> add merge_resources script

- scripts/partial.pl
a script for partial tab completion in Irssi
For another implementation of the same idea, check
https://github.com/aquanight/codejunk/blob/master/perl/irssi/bash_tab.pl
> add partial script

- scripts/discord_unbridge.pl
> Fix for issue #729

- scripts/chansearch.pl
> [chansearch] update web page filter

- scripts/chansearch.pl
> [chansearch] v2.3

- scripts/fpaste.pl
> [fpaste] v0.02

- _testing/config.yml
- scripts/iMPD.pl
> [iMPD] fix compile error

- scripts/imdb.pl
> [imdb] v1.03

- scripts/shorturl.pl
\- https://metamark.net/
\+ self check
@tsaavik
> [shorturl] update

- scripts/google.pl
> [google] v2.01

- scripts/duckduckgo.pl
> [duckduckgo] v0.02

- scripts/0x0st.pl
> [0x0st] v0.04

- scripts/lastfm.pl
> [lastfm] v5.9

- scripts/urlgrab.pl
Added timestamp to urllog file.
> [urlgrab] improve url log file format

- scripts/matterircd_complete.pl
For https://github.com/42wim/matterircd networks, supports tab auto completion (or key binding)
for nicks and message/threads.
> [matterircd_complete.pl] Add new matterircd_complete.pl script

- scripts/print_signals.pl
Changelog:
* Unload signal handlers when script is unloaded
* Update list of signals from upstream
> [print_signals.pl] New version 1.2

- scripts/spellcheck.pl
@jwilk
jwilk/irssi-spellcheck#4
check for changes by <https://github.com/bw1/check-irssi-scripts> ones a week
> [spellcheck] v0.9.1

- scripts/adv_windowlist.pl
- add /set awl_custom_key_re, to display custom keys in the $Q expando
fixes #781
> [adv_windowlist] update to 1.10

- scripts/perlalias.pl
> New perlalias v2

- scripts/colon_emoji.pl
If your colon emoji completes, this will get processed now
> [colon_emoji] Add tab completion signal
