- scripts/rainbow.pl
Before, I was getting:
```
12:55:46 -!- Irssi: Error in script rainbow:
12:55:46 Undefined subroutine &Encode::_utf8_on called at /home/m/.irssi/scripts/autorun/rainbow.pl line 50.
```
> Use the Encode module in rainbow.pl

- scripts/send_scroll.pl
The send_scroll script scrolls the window to the end before permitting
to send new messages. Useful in case you like to forget this.
> Add new script send_scroll.pl

- scripts/hilightwin.pl
Escape any %-code so that it doesn't turn into colours.
> Fix formatting codes in hilightwin

- scripts/accent.pl
- scripts/fortune.pl
Some scripts have Rcs Id as version, this displays weirdly on s.i.o now
> Normalise version info from rcsid

- .travis.yml
- _testing/_irssi_test.pl
- _testing/travis/update-scripts-yaml.pl
The YAML module that available in the Travis repos does not enforce
marking of numeric-looking variables as strings. When these are parsed
by the github site generator, precision is lost as they are interpreted
numerically (eg. version: 1.10 -> turns into 1.1).
Reported by Vilkku. Fixes #125
This is an issue with the new YAML autogeneration.
> Correctly preserve non-numeric version numbers

- scripts/people.pl
I think another script of mine was breaking it, so people.pl couldn't
load its own config file as it thought the whole thing was one massive
line.
> Set record break char to newline when loading config file in people.pl

- scripts/dau.pl
- scripts/dejunk.pl
- scripts/hlbot.pl
- scripts/ircgallery.pl
- scripts/news.pl
- scripts/xauth.pl
Follow-up to #129 to fix all $/ inside the scripts archive. Also fix
dejunk to not break scripts using the assumed default. Note, other
scripts like cmpchans might still break your scripts due to the global
nature of the Perl.
> Localise the $/ special variable.

- scripts/scriptassist.pl
This is a regression introduced in
c5ad61b4b0166f7cb769f23dfece2a5d4e62bd6e where one `defined' statement
got removed in error while cleaning up warnings. Fixes #134
> Fix scriptassist broken on unload

- scripts/spellcheck.pl
Stops unnecessary spelling corrections being generated when pasting urls.
> spellcheck.pl - Fix for urls

- scripts/email_msgs.pl
This script is based on email_privmsgs.pl v0.5 from Adam James:
https://github.com/irssi/scripts.irssi.org/blob/ac4229402acecd02aad24e874316b9d2c6d1a9d2/scripts/email_privmsgs.pl
email_msgs.pl provides advanced features and customization options
in comparison to email_privmsgs.pl:
* support for public messages as well (with/without mentions);
* support for own messages as well;
* configuration options to select what messages should be emailed:
- public received;
- private received;
- private sent;
- public sent;
- public mentions received.
* configuration option to choose whether the user must be away or not;
* configuration option to select message check/email interval;
* configuration option for the destination email address;
* configuration option to activate detailed info:
- currently …
> Adds irssi perl script email_msgs.pl:

- scripts/8-ball.pl
I've had a rename since back when this script was written. Also, the old email address is soon deprecated.
> Updating author details

- scripts/screen_away.pl
Loading the script on my Fedora 21 suddenly failed. It seems that the regex did not match the socket path. I believe this was in conjunction with upgrading screen to version `4.03.01`. Small changes to the regex solved it, maybe this would be usefull to others as well.
Changed .+ to .* at both sides of the line and removed newline character.
> Edited regex for socket_path search.

- scripts/hilightwin.pl
Also remove the prepended timestamp, since CLIENTCRAP already has one
Fixes #163
> hilightwin.pl: Use CLIENTCRAP level instead of NEVER to allow logging

- scripts/xdcc_autoget.pl
xdcc_autoget allows users to store lists of xdcc bots and search terms. On a regular basis, the search terms will be fed to the bots, and their responses parsed, and new files that match each search term will be downloaded for each bot. The idea is that it automates the normally cumbersome process of finding and downloading new xdcc packs for active TV series, or other packs that the user wishes to download as soon as they are available.
> Added xdcc_autoget userscript

- scripts/mh_windowfill.pl
fill windows so scrolling starts bottom-up instead of top-down (screenshots in source)
changes:
call windowfill* directly from signals
removed on load timeout
> mh_windowfill.pl v1.04

- scripts/mh_userstatus.pl
Show in channels when users go away/back or oper/deoper
Will periodically check the channels you are on for users changing their away/oper status and print a line like:
-!- <nick> [<userhost>] is now gone
-!- <nick> [<userhost>] is now here
-!- <nick> [<userhost>] is now oper
-!- <nick> [<userhost>] is now not oper
You can also list the currently away or opered users with the commands /whoa and /whoo respectively
>  mh_userstatus.pl v1.00

- scripts/adv_windowlist.pl
- workaround for crash due to infinite recursion in irssi's Perl
error handling
> adv_windowlist 1.0a6

- scripts/history_search.pl
- scripts/ido_switcher.pl
- scripts/per_window_prompt.pl
- accept ^M in addition to ^J as enter key for scripts which use raw gui key pressed
(won't solve KP_ENTER issue)
> script fixes for the icrnl change in irssi

- scripts/active_notice.pl
Fixes notices appearing with markup if the line starts with a % sign. For example, a line beginning with %I would appear inversed.
> Fix escaping for active_notice.pl when a line starts with a percent sign

- _testing/config.yml
- scripts/desktop-notify.pl
This script sends notification using the Desktop Notifications Specification.
It depends on libnofity, perl-glib-object-introspection and perl-html-parser
packages.
> Added desktop-notify 1.0.0

- scripts/fnotify.pl
The fnotify.pl script can now ignore hilights of a chosen priority == fnotify_ignore_level.  The script has hooked "setup changed" so that it doesn't need to be restarted every time fnotify_ignore_level is changed.
> Fnotify 0.0.6

- scripts/nickserv.pl
Freenode includes control characters in its notices, so strip these.
Also removes a redundant regexp from the if clause for /msg NickServ
style services.
> nickserv.pl: Add support for Freenode and irc.perl.org

- scripts/dim_nicks.pl
- optionally ignore hilighted lines, reported by vague
> update dim_nicks to v0.4.8

- scripts/cgrep.pl
$start and $realname declarations have been commented out due to a change in code. This causes a problem due to the use of "use strict" (warnings). This new declaration solves the issue.
> FIX: start and realname declaration

- scripts/ident.pl
* Read passwords from ~/.irssi/passwords. One entry per line, space-separated network tag and password
* When prompted by NickServ to identify, do so using /^quote nickserv
> Add ident.pl - automatically identify from file-based pws

- scripts/hilite_url.pl
This script does nothing else than just print URLs in public messages in blue and underlined, so you never miss a link that's posted in a channel
> Simple script that just highlights URLs in public messages

- index.html
Auto-correction is often disruptive to searches in this field where
arbitrary strings are frequently the correct item to search for.
> Disable auto-correction of the search input

- scripts/invitejoin.pl
- scripts/nickserv.pl
Please accept my PR, since it might be of use to others.
The following changes solve the issue of being able to reauthenticate and rejoin a restricted channel after a disconnect on https://hackint.org/services where you have to request an invite to such a channel.
0. When you have a disconnect you will eventually reconnect with a different nick until the old user is removed.
1. keepnick will notice that and change the nick back
2. nickserv will handle authentication
2.1. the new postcmd allows to ask ChanServ for an invite to the restricted channel
3. invitejoin will accept the invite and join the restricted channel
3.1 the new allowed users list will only accept invite from ChanServ ...
I tried to use the already present style of loading / storing settings and extended the help dialogs.
> Handle nickserv on reconnect

- scripts/print_signals.pl
This script writes signals and their data to a file. The purpose is to aid developers working with signals. Options exist to limit the signals to a subset, as well as to exclude signals.
X-Licence: MIT
Signed-off-by: martin f. krafft <madduck@madduck.net>
> New script to aid with signal inspection

- scripts/postpone.pl
This adds `discard`, which removes messages, but unlike `flush` it does not actually send them.
Signed-Off-By: martin f. krafft <madduck@madduck.net>
> [postpone.pl] Subcommand to discard (not flush) messages

- scripts/go.pl
This introduces a few settings, allowing the behaviour of `go.pl` to be configured:
- `go_match_case_sensitive` (default:true), match channel names case-sensitively
- `go_complete_case_sensitive` (default:false), complete channel names case-sensitively
- `go_match_anchored` (default:true), match channel names only at start of word
- `go_complete_anchored` (default:true), complete channel names anchored at start of word
Signed-off-by: martin f. krafft <madduck@madduck.net>
> [go.pl] Make matching behaviour configurable

- scripts/ctrlact.pl
In the absence of a network tag passed to the `query` subcommand, no
rules but the default would match and so the returned match(es) would
potentially not actually be the ones used in context of ctrlact's normal
operation.
This commit fixes #354 by special-casing the threshold match when the
data to be looked up doesn't actually specify a network tag. In this
case, the output for net will be '(ignored)'.
> [ctrlact] Fix network matching for query subcommand

- scripts/iquiz.pl
- scripts/iquiz_en.pl
- added optional automatic hints
- made /quiz or /help quiz commands to show only options for selected quiz type (the list was too wide to comprehend)
- !podp no longer shows already revealed hint/answer
- script informs player about achieving point limit in 50%+1 mode
- team order is sorted by join time (Familiada)
- option to reset/keep team players in their teams (aside of individual points) (Familiada)
- some minor fixes
> Update iQuiz to new version.

- scripts/signal_hilight.pl
When a user is away, this script sends highlighted messages via Signal.
I didn't update `_data/scripts.yaml` since it looks like it's automatically built.
If there's anything else you need, please let me know!
> Add script to send highlighted messages via Signal

- scripts/pushsafer.pl
Plugin for irssi (a console based IRC client) to send push-notifications using https://www.pushsafer.com.
This allows you to be notified when someone messages/mentions you on IRC, 
when you're not online.
1. register or login inot your pushsafer control panel abd note your private or alias key.
2. cp pushsafer.pl to ~/.irssi/scripts/ and symlink into scripts/autorun if you desire.
3. touch ~/.irssi/pushsafer_ignores
4. Within irssi: 
1. /load autorun/pushsafer.pl
2. /set pushsafer_key "your pushsafer private or alias key"
3. optional set the following params https://www.pushsafer.com/en/pushapi
4. /set pushsafer_device "device or device group id"
5. /set pushsafer_sound "sound number"
6. /set pushsafer_icon "icon number>
7. /set pushsafer_vibration "vibration 0-3>
8. /set pushsafer_url …
> Add pushsafer.com notification service

- scripts/go2.pl
This switches the order of changing windows and clear the prompt. Now
the prompt line is cleared before the `go` command is called, which
means that scripts like per_window_prompt.pl won't save the `/go`
command.
Signed-off-by: martin f. krafft <madduck@madduck.net>
> [go2.pl] clear prompt before changing windows

- scripts/trigger.pl
Server notices are included in the privnotices type, but their address parameter is undefined, because the prefix of the message is just the server name.  By defaulting address to an empty string in the masks match, we can match server notices easily with `-privnotices -masks '<servername>!'` instead of a really messy rawin + regexp.  (Irssi merges the nick and address passed into masks_match with a `%s!%s` format string, so there'll be a trailing "!" when address is an empty string.)
> trigger.pl: default address to empty in mask match

- scripts/colorize_nicks.pl
reported by SCHAPiE, fix by vague and Grinnz
> stop perl being confused by ][ in regex

- scripts/ls.pl
Following things were changed:
1. The script won't crash when invalid regex pattern is provided as an argument to `/ls`
2. `/ls` informs when there are no matches
3. Results from each `/ls` invocation are separated by `--- Search results:`
4. Minor style fixes
> Updates to ls.pl

- scripts/autorejoin.pl
This merges the idea of `autorejoin_channels` from the version of the script at http://wouter.coekaerts.be/irssi/scripts/autorejoin.pl
The version in this repository had different indentation and the timeout delay stuff, so the end result is nothing like that one. Also that one says Public Domain. Whatever.
This adds two settings:
- `autorejoin_delay`: time in seconds, defaults to 5, as the old code. Can be set to 0 to autorejoin instantly (like the other script)
- `autorejoin_channels`: channels whitelisted for autorejoin, applies to all channels if empty.
Not a fan of having this enabled for all channels, but it's the most backwards-compatible behavior with the version of the script that was in this repo. The other version defaulted to nothing.
This also changes the `timeout_add` into …
> autorejoin: Add settings, general cleanup

- scripts/account-notify.pl
The script simply displays a message when people identify to an account
(or log out of one) on servers supporting the account-notify CAP.
> Add account-notify.pl

- _testing/travis/autoinstall-perl-prereqs.zsh
- empty filelist can happen on module removal (see #448 )
- triggered the default behaviour of the module scanner, which will then scan more files than it should
- uncovered missing version handling (`~` syntax)
> fix bug with empty filelist and add code for missing modver handling

- scripts/anames.pl
this seems like the correct change, we should not overwrite the who redirection. Reported by unit193. Fixes #444
> anames.pl: Drop re-registration of WHO

- scripts/timer.pl
* Remove finished timers during their last cycle, rather than one
interval after
* Allow timer names to contain anything other than whitespace
> timer.pl: minor improvements

- scripts/hlscroll.pl
With newer versions of irssi, using hlscroll results in this error message:
```
Can't locate object method "view" via package "Irssi::UI::Window"`
```
Thanks to: Nei[e] on #irssi (freenode)
> Unbreak hlscroll on recent versions of irssi

- scripts/mpd.pl
I just escaped the braces in the regex statements as it becomes an error that lets the script crash in the current version of perl
> [mpd.pl] unescaped left brace in regex becomes an error in perl5 v26

- scripts/nickserv.pl
Anope has a slightly different message for the "If this is ..." line,
modify the existing regex to also catch this message:
"(If this is your nick, type /msg NickServ IDENTIFY password.)"
> [nickserv] Add detection of Anope IRC Services

- scripts/colon_emoji.pl
sub sig_send was defined 2 times, with the same code.
I removed 1 of them.
> [colon_emoji] remove dead code

- scripts/nicklist.pl
In screen mode, nicklist.pl uses the obscure escape sequences CSI s and
CSI u to save and restore the cursor position; on top of that, it uses
ESC P to bypass screen's interpretation of these escape sequences, passing
them directly to the underlying terminal.
While I did not investigate whether this makes sense at all - bypassing
screen's position tracking seems dangerous at best - this fix improves
terminal compatiblity by replacing CSI s and CSI u with the more common
ESC 7 and ESC 8 sequences [1].
The issue surfaced then vte3 replaced their parser, removing support for
CSI s and CSI u [2]. While support has been restored in the latest master
[3], using the more compatible escape sequences in nicklist.pl generally
seems like a good idea.
[1] https://gitlab.gnome.org/GNOME/vte/issues/48 …
> [nicklist] Improve terminal compatiblity of screen mode

- scripts/adv_windowlist.pl
- fix crash on invalid /set awl_sort, introduced in 1.6, reported by @tpetazzoni (fixes #542)
- delay viewer initialisation
- improve race condition on tmux resize integration
> [adv_windowlist] update to 1.7

- scripts/savecmdhist.pl
Saves the commands you typed in the input prompt to a history file, so that they persist across /upgrade and restart.
> [savecmdhist] new script to save the input prompt history to a persistent history file

- scripts/server_time.pl
This script implements IRCv3's server-time extension for most users'
purposes. For example, ZNC users can use this plugin to get clean
playback buffers.
I've updated this script to drop a dependency I had to download from
CPAN when I started using it. I did not initially create this script,
but I can provide support going forward. My repo for issues is at
https://github.com/itsjohncs/irssi-server-time (mentioned in the
script as well).
I plan to implement the server-time extension in irssi's core myself
eventually, so maintaining this script seems fitting.
> [server_time] sneak in server-time extension.

- scripts/ignore_join_blob.pl
This script solves the issue [described here](https://github.com/irssi/irssi/issues/992) where the text displayed on join is unignorable despite them being of the level CRAP.
> ignore_join_blob: ignore text displayed when (re)joining a channel

- scripts/oops.pl
ll is aliased to `ls -l` on a lot of distributions by default and has made its
way into (at least my) muscle memory right next to regular ls.
> [oops] Also call /names on ll

- scripts/go.pl
example: currently `/go #vim` when `#vim` and `#vim-ale` are both open will incorrectly go to `#vim-ale` depending on the order of your windows. this fixes that.
> go.pl: fix short circuiting during channel search

- _testing/autoinstall-perl-prereqs.zsh
> Fix quoting of version requirements in autoinstall-perl-prereqs

- scripts/elist.pl
Adds an optional argument (`-yes`/`-YES`) that allows users to pass `-YES` to the underlying `/LIST` command when required. Irssi warns the user and prompts for this option when required.
Fixes #630
> [elist] Add optional -yes/-YES option

- scripts/fnotify.pl
fnotify allows you to do things like turn on blinkenlights when you are
hilighted in messages. Adding your own messages allows you to turn off
any local notifications once you respond.
Sample of how to do this is at
https://github.com/mrda/junkcode/blob/master/irssi-notify.sh
> [fnotify] Add own messages to fnotify writes

- scripts/dtach_away.pl
This forks and rewrites the `screen_away.pl` script into a new `dtach_away.pl` one. It's kind of hackish: maybe it would be best to add support for dtach into the existing script, but I found it easier to proceed that way because the capabilities of the two programs are not the same (save the executable bit on the socket, see https://github.com/crigler/dtach/issues/17#issuecomment-553577118).
This drops the socket autodetection. There's no equivalent to `screen -ls` in dtach, so that doesn't work. We could do process tracing with lsof to figure it out, but that seems horrible and it seems like minimal config to ask the user for the socket path.
Works for me anyways, I always use the same socket for IRC.
> [dtach_away] add support for dtach

- _testing/config.yml
- scripts/mh_secureonlychan_489.pl
For users who are forced/prefer to use an older version of Irssi but still want this little issue fixed.
Fix for Irssi not fully supporting numeric 489 ERR_SECUREONLYCHAN.
see https://github.com/irssi/irssi/issues/1193 for details about the issue.
This script will display an error message in the status-window if you try to join a secure only channel without a secure connection. If you have the setting autoclose_windows off, you will still get the old raw message in the channel-window too.
The script will die gracefully with a message if loaded in a version of Irssi that already have the source-code fixed (ABI version 29 or higher).
see https://github.com/irssi/irssi/pull/1196 for details about the code fix.
> mh_secureonlychan_489 v1.00

- scripts/mh_secureonlychan_489.pl
Fixed a typo causing the script to selfdestruct on ABI version 28 and later instead of the correct 29 and later.
> [mh_secureonlychan_489] update from v1.00 to v1.01

- scripts/bansearch.pl
* Adjust set-by-server check to not be freenode-specific
* Make $~a check work
* Add $a check
* Make $x check work for all cases
* Shift mode redirect to block where mode request is sent
* Add debug output and setting to control it
> bansearch: various fixes and improvements

- scripts/ez_color.pl
A single, simple helper function to easily wrap strings in mIRC-compatible formatting codes.
> add script: ez_color.pl

- scripts/long_messages.pl
a script that automatically downloads and dumps long messages sent by Matrix
IRC bridge users
> add long_messages script

- scripts/autorealname.pl
```
14:34 < Danny_B> hi, i'm suddenly getting this error when starting irssi:
14:34 < Danny_B> -!- Irssi: Error in script autorealname:
14:35 < Danny_B> Can't call method "nick_find" on an undefined value at /path/to/autorealname.pl line 282.
14:35 < Danny_B> using irssi 1.0.7-1~deb9u1 (20180213 0139)
14:36 < Danny_B> any idea what might went wrong?
14:36 < Danny_B> thank you
14:37 < Danny_B> (the autorealname.pl is $VERSION = "0.8.6";
14:37 < Nei> maybe a bug in the script 
```
> [autorealname] bug fix

- scripts/chankeys.pl
This plugin serves to simplify the assignment of keyboard shortcuts that take you to channels or queries (so-called "window items").
Let's assume you're in the #irssi channel, then you could issue the command
```
/chankey meta-s-meta-i
```
and thenceforth, hitting that key combination will take you to the channel. It's smart enough to check whether a mapping is already in use by chankey, or whether a key combination won't work, for instance because meta-s was already assigned elsewhere in the above.
You can also explicitly specify the name (and chatnet) if you'd like to set up a mapping for another item:
```
/chankey F12 &bitlbee
```
Key bindings are removed when you leave a channel or a query is closed, and reinstated when the channel or query is reinstated. They are saved to …
> [chankeys.pl] New script to control keyboard to channel shortcuts

- scripts/trigger.pl
For those of us keeping config in Git, it's a bit annoying when trigger changes the order based on the time of day and moon phase (i.e. hash order is undefined) on each config save, so let's sort the lines to make it a bit more idempotent.
Signed-off-by: martin f. krafft <madduck@madduck.net>
> [trigger.pl] Sort trigger filters prior to save for idempotency

- scripts/tab_stop.pl
This changes the default behaviour to make TAB replacements line up. To get the original behaviour, the user will need to do `/set
tabstop_interval 0` explicitly.
> [tab_stop.pl] Implement tab stops with configurable length

- scripts/leodict.pl
Minor addition to allow users to set and use proxies for leodict.pl's requests to the leo website. Helpful for certain setups and networks where proxies are required, but not all irssi traffic may be easily tunneled.
> [leodict] Add proxy support for requests made to dict.leo.org

- scripts/elist.pl
Added an option to have the channels list printed with colors stripped from topic text.
use: "/set elist_colorized ON/OFF" to change behavour (default is ON)
> [elist.pl] added option to remove colors from topics

- scripts/suppress_yubikey_otp.pl
Old script behaviour: match on 6 c characters
Yubikey OTP format: 4 c followed by 40 other modhex characters
New script regex matches better for less public shame with yubikey nano-c
> yubikey: update regex

- scripts/mail.pl
hi,
mail.pl refers to /SET MAILDIRMODE which is wrong, the script registers option maildir_mode
commit fixes this.
> mail.pl: show correct option in manual
